name: freshcut_test
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui packages
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  very_good_analysis: ^2.4.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/
    - assets/gifs/

  fonts:
    # Add fonts to the application.
    - family: Grotesk
      fonts:
        - asset: assets/fonts/AktivGrotesk-Regular.ttf
        - asset: assets/fonts/AktivGrotesk-Medium.ttf
          weight: 700
